### ISSUE TITLE
Dockerfile中FROM java可能不太合适

### ISSUE THREAD

**Issue by JohnNiang** [JaredTan95/TMCloud#1]
指定一个tag比较好

```
FROM java:8
...
```

**Comment by JaredTan95** [comment]
确实，这是很早之前的记录了，我一般在用的时候都会使用jre-alpine,比如：FROM openjdk:8-jre-alpine，这样可以极大的压缩镜像大小。

**Comment by JohnNiang** [comment]
我也刚刚发现，就一个普通的java:8 pull下来之后竟然后643MB，然后发现它已经被抛弃了。用了openjdk:8-jre-alpine，只占用了83M，简直不能比。
